/**
 * ===== RPG STRIKER ANIMATION FUNCTION =====
 * Autogenerated & exported separately.
 * 
 * Instructions to include this inside custom loops (Phaser, Three, Canvas2D, Pixi):
 * - Call this within your frame update routine.
 * - Translate the Canvas context so that (0, 0) is the center of your character before running.
 * 
 * @param {CanvasRenderingContext2D} ctx - Target Canvas 2D graphics render pipeline context
 * @param {object} c - Configuration dimensions and colors
 * @param {number} c.radius - Core avatar radius (offset orbit base path)
 * @param {string} c.primaryColor - Primary emission/glowing neon hex key
 * @param {string} c.secondaryColor - Secondary highlight tint hex key
 * @param {number} c.glow - ShadowBlur glow expansion scale
 * @param {number} c.lineWidth - Line trace stroke thickness
 * @param {number} c.particleCount - Number of swirling particle beads
 * @param {number} time - Animation time elapsed in ticks
 */
window.drawStrikerEffect = function(ctx, c, time) {
  // ===== GAIA STRIKER =====
  const blades = 16;
  ctx.save();
  ctx.rotate(time * 1.5);
  
  for (let i = 0; i < blades; i++) {
      ctx.save();
      ctx.rotate((i * Math.PI * 2) / blades);
      
      ctx.beginPath();
      ctx.moveTo(0, c.radius + 2);
      // Sweeping curved triangular blade
      ctx.quadraticCurveTo(15, c.radius + 15, 20, c.radius + 25);
      ctx.quadraticCurveTo(0, c.radius + 20, -5, c.radius + 2);
      
      const isMagenta = i % 2 === 0;
      ctx.fillStyle = isMagenta ? c.secondaryColor : c.primaryColor;
      ctx.shadowBlur = c.glow;
      ctx.shadowColor = ctx.fillStyle;
      ctx.fill();
      ctx.restore();
  }
  
  // Inner solid boundary band
  ctx.beginPath();
  ctx.arc(0, 0, c.radius + 5, 0, Math.PI*2);
  ctx.strokeStyle = c.secondaryColor;
  ctx.lineWidth = 4;
  ctx.stroke();
  ctx.restore();
};
