/**
 * ===== RPG STRIKER ANIMATION FUNCTION =====
 * Autogenerated & exported separately.
 * 
 * Instructions to include this inside custom loops (Phaser, Three, Canvas2D, Pixi):
 * - Call this within your frame update routine.
 * - Translate the Canvas context so that (0, 0) is the center of your character before running.
 * 
 * @param {CanvasRenderingContext2D} ctx - Target Canvas 2D graphics render pipeline context
 * @param {object} c - Configuration dimensions and colors
 * @param {number} c.radius - Core avatar radius (offset orbit base path)
 * @param {string} c.primaryColor - Primary emission/glowing neon hex key
 * @param {string} c.secondaryColor - Secondary highlight tint hex key
 * @param {number} c.glow - ShadowBlur glow expansion scale
 * @param {number} c.lineWidth - Line trace stroke thickness
 * @param {number} c.particleCount - Number of swirling particle beads
 * @param {number} time - Animation time elapsed in ticks
 */
window.customStrikerEffect = function(ctx, c, time) {
  // ===== ROULETTE STRIKER =====
  ctx.save();
  ctx.rotate(time * 0.5);
  ctx.lineWidth = 10;
  ctx.strokeStyle = c.primaryColor;
  ctx.shadowBlur = c.glow; 
  ctx.shadowColor = c.primaryColor;
  
  // Outer segmented purple ring
  const circ = Math.PI * 2 * (c.radius + 12);
  ctx.setLineDash([circ / 24 - 2, 2]);
  ctx.beginPath();
  ctx.arc(0, 0, c.radius + 12, 0, Math.PI * 2);
  ctx.stroke();
  
  // Inner solid thin ring
  ctx.setLineDash([]);
  ctx.lineWidth = 2;
  ctx.strokeStyle = c.secondaryColor;
  ctx.beginPath();
  ctx.arc(0, 0, c.radius + 2, 0, Math.PI * 2);
  ctx.stroke();
  
  // Inner ticking marks
  ctx.lineWidth = 4;
  ctx.beginPath();
  ctx.arc(0, 0, c.radius - 4, 0, Math.PI * 2);
  ctx.setLineDash([2, circ / 36]);
  ctx.stroke();
  ctx.restore();
};
